# Use o KubernetesExecutor para que cada tarefa rode num Pod isolado.
executor: KubernetesExecutor

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/samuel-aka-viana/salesforce-mock-orquestration.git"
    branch: "main"

ingress:
  web:
    enabled: true
    hosts:
      - host: airflow.local
        paths:
          - path: /
            pathType: ImplementationSpecific

data:
  postgresql:
    persistence:
      enabled: true
      storageClassName: "local-path"
      size: 5Gi

fernetKey:
  generate: true