executor: KubernetesExecutor

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/samuel-aka-viana/salesforce-mock-orquestration.git"
    branch: "main"

ingress:
  web:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - name: "airflow.local"
        tls:
          enabled: false
    path: "/"
    pathType: "Prefix"

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 5Gi

fernetKeySecretName: "airflow-fernet-key"
fernetKeySecretKey: "fernet-key"
